/**
 * iDatanomics
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CardModel } from './cardModel';
import { SymbolModel } from './symbolModel';


export interface GraphicChartData {
    graphicChartId?: string;
    name?: string;
    createdBy?: string;
    symbolList?: Array<SymbolModel>;
    cardList?: Array<CardModel>;
}
