/**
 * iDatanomics
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TagInfo {
    id?: string;
    name?: string;
    alias?: string;
    units?: string;
    max?: number;
    min?: number;
    dataType?: string;
    source?: string;
    description?: string;
    location?: string;
}
