swagger: '2.0'
info:
  title: iDatanomics
  version: 1.0.0
host: localhost:5000
schemes:
  - http
basePath: /api
produces:
  - application/json
security:
  - basic: []
  - oauth: []
securityDefinitions:
  basic:
    type: basic
    flow: password
  oauth:
    type: oauth2
    flow: password
paths:
  /Token:
    get:
      tags:
        - Token
      operationId: GetToken
      responses:
        '200':
          description: Success
          schema:
            type: string
            description: token
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
  /Resolutions:
    get:
      tags:
        - Resolution
      operationId: GetResolutions
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/ResolutionList'
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
  /Tags:
    get:
      tags:
        - Tag
      operationId: GetTags
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/TagList'
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
  /Background:
    post:
      consumes:
        - multipart/form-data
      parameters:
        - name: imgFile
          in: formData
          required: false
          type: file
        - name: graphicChartId
          in: formData
          required: true
          type: string
        - name: width
          in: formData
          required: true
          type: number
        - name: height
          in: formData
          required: true
          type: number
        - name: bgSizeOption
          in: formData
          required: true
          type: string
      operationId: SaveBackground
      tags:
        - Background
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
  /Background/{graphicChartId}:
    delete:
      tags:
        - Background
      operationId: RmBackground
      parameters:
        - name: graphicChartId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
  /Background/Img/{graphicChartId}:
    get:
      tags:
        - Background
      operationId: GetImg
      produces:
        - image/png
        - image/gif
        - image/jpeg
      parameters:
        - name: graphicChartId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Success
          content:       # Response body
            image/*:     # Media type
              schema: 
                type: string
                format: binary
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
  /Background/Info/{graphicChartId}:
    get:
      tags:
        - Background
      operationId: GetInfo
      parameters:
        - name: graphicChartId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/BackgroundInfo'
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
  /GraphicChart:
    post:
      tags:
        - GraphicChart
      operationId: SaveGraphicChartData
      parameters:
        - name: graphicChartData
          in: body
          required: true
          schema:
            $ref: '#/definitions/GraphicChartData'
      responses:
        '200':
          description: Success
          schema:
            type: string
            description: chart id
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
    get:
      tags:
        - GraphicChart
      operationId: GetGraphicChartList
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GraphicChartList'
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
  /GraphicChart/{graphicChartId}:
    get:
      tags:
        - GraphicChart
      operationId: GetGraphicChartData
      parameters:
        - name: graphicChartId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/GraphicChartData'
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
    delete:
      tags:
        - GraphicChart
      operationId: RmGraphicChartData
      parameters:
        - name: graphicChartId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
          schema:
            type: string
        '403':
          description: Forbidden
          schema:
            type: string
        '500':
          description: >-
            (Internal Server Error) An exception or an error happens in portal backend.
          schema:
            type: string
            description: Error
definitions:
  ResolutionList:
    type: array
    items:
      $ref: '#/definitions/CanvasResolution'
  CanvasResolution:
    type: object
    properties:
      x:
        type: number
      y:
        type: number
      viewValue:
        type: string
  TagList:
    type: array
    items:
      $ref: '#/definitions/TagInfo'
  TagInfo:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      alias:
        type: string
      units:
        type: string
      max:
        type: number
      min:
        type: number
      dataType:
        type: string
      source:
        type: string
      description:
        type: string
      location:
        type: string
  BackgroundInfo:
    type: object
    properties:
      width:
        type: number
      height:
        type: number
      bgSizeOption:
        type: string
      imgContentType:
        type: string
  GraphicChartList:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        createdBy:
          type: string
        lastEditedAt:
          type: string
          format: date-time
          x-chance-type: date
  GraphicChartData:
    type: object
    properties:
      graphicChartId:
        type: string
      name:
        type: string
      createdBy:
        type: string
      symbolList:
        type: array
        items:
          $ref: '#/definitions/SymbolModel'
      cardList:
        type: array
        items:
          $ref: '#/definitions/CardModel'
  SymbolModel:
    type: object
    properties:
      symbolId:
        type: string
      symbolType:
        type: string
      tagId:
        type: string
      tagName:
        type: string
      viewBox:
        type: string
      viewBoxWidth:
        type: number
      viewBoxHeight:
        type: number
      positionXRatio:
        type: number
      positionYRatio:
        type: number
      widthRatio:
        type: number
      strokeRGB:
        type: string
  CardModel:
    type: object
    properties:
      cardId:
        type: string
      positionXRatio:
        type: number
      positionYRatio:
        type: number
      widthRatio:
        type: number
      heightRatio:
        type: number
      strokeRGB:
        type: string
      alpha:
        type: string
      zOrder:
        type: number



